# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
