# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Student'),
        ),
    ]
